# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#

default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['DB_USERNAME'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: profile_development
  password: <%= ENV['DB_PASSWORD'] %>

test:
  <<: *default
  database: tprofile_test
  password: <%= ENV['DB_PASSWORD'] %>

production:
  <<: *default
  database: profile_production
  password: <%= ENV['DB_PASSWORD']  %>